{
  "comments": [
    {
      "key": {
        "uuid": "Pynuem10",
        "filename": "libc/bionic/stubs.cpp",
        "patchSetId": 3
      },
      "lineNbr": 63,
      "author": {
        "id": 1003723
      },
      "writtenOn": "2013-02-12T02:23:30Z",
      "side": 1,
      "message": "seems odd that the behavior is to return errno but not set it.",
      "revId": "2a1bb4e64677b9abbc17173c79768ed494565047",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "Pyhvsv7E",
        "filename": "libc/bionic/stubs.cpp",
        "patchSetId": 3
      },
      "lineNbr": 63,
      "author": {
        "id": 1003224
      },
      "writtenOn": "2013-02-12T02:33:07Z",
      "side": 1,
      "message": "it\u0027s common in a lot of these _r functions (and \"new\" POSIX API in general). my guess is that a different committee was working out thread-local errno and the two groups never talked to one another :-)",
      "parentUuid": "Pynuem10",
      "revId": "2a1bb4e64677b9abbc17173c79768ed494565047",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889",
      "unresolved": false
    }
  ]
}