{
  "comments": [
    {
      "unresolved": true,
      "key": {
        "uuid": "b5f0c068_dbedf8a0",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 4
      },
      "lineNbr": 0,
      "author": {
        "id": 1873222
      },
      "writtenOn": "2024-08-18T00:18:16Z",
      "side": 1,
      "message": "Re failures:\n\nSeems like /bin/env is not available on some systems? Is python?\nPerhaps I should just invoke python3 directly.\n\n```\n/bin/env: bad interpreter: No such file or directory\n```",
      "revId": "cbec62a6d269ad172ff33c781579371a57d1b3f3",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889"
    },
    {
      "unresolved": true,
      "key": {
        "uuid": "f8cd1f07_b20a18b5",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 4
      },
      "lineNbr": 0,
      "author": {
        "id": 1873222
      },
      "writtenOn": "2024-08-19T19:44:34Z",
      "side": 1,
      "message": "It may be that it should be `/usr/bin/env python3` instead. Mimicking https://cs.android.com/android/platform/superproject/main/+/main:bionic/libc/tools/gensyscalls.py;l\u003d1;drc\u003db53e48f1246f9719a39af84808830421a6c8bd4b now.",
      "parentUuid": "b5f0c068_dbedf8a0",
      "revId": "cbec62a6d269ad172ff33c781579371a57d1b3f3",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889"
    },
    {
      "unresolved": true,
      "key": {
        "uuid": "9b8181f0_3abc4786",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 4
      },
      "lineNbr": 0,
      "author": {
        "id": 1003224
      },
      "writtenOn": "2024-08-19T20:44:37Z",
      "side": 1,
      "message": "(yeah, i think debian doesn\u0027t have a \"python\" any more, so that come the python3 to python4 transition, they don\u0027t have the same ambiguity problem they had from python2-but-actually-just-called-python to python3 :-) )",
      "parentUuid": "f8cd1f07_b20a18b5",
      "revId": "cbec62a6d269ad172ff33c781579371a57d1b3f3",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "4cdc3a1c_c95ec96a",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 4
      },
      "lineNbr": 0,
      "author": {
        "id": 1873222
      },
      "writtenOn": "2024-08-19T21:12:22Z",
      "side": 1,
      "message": "Seems to be working now! Yeah, it was probably just the `python`. Thanks!",
      "parentUuid": "9b8181f0_3abc4786",
      "revId": "cbec62a6d269ad172ff33c781579371a57d1b3f3",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889"
    }
  ]
}